### ISSUE TITLE
ensure Ubuntu OVA 16.04 webpack-dev-server runs

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/install_taxonworks#13] opened 2018-04-13 17:04 UTC
See #10 for background. 

* Need to integrate NPM memory update.
* Might need to add a rake task that curates the system after NPM updates

**Comment by LocoDelAssembly** [comment] 2018-04-16 20:37
@JeGoi I'm in the process of rebuiding the VM from scratch, and when trying the increase-memory-limit tool, I get a difference in the files (but not an extension of 4096 but rather 10240). However when trying to run the .bin/webpack-dev-server it just freezes consuming 100% CPU (even if I hand-edit the line to 4096 or use `LIMIT=4096 increase-memory-limit`)... Have you experienced exactly the same thing or it just continued with the out of memory problem?

What it does work (but cannot guarantee it is 100% equivalent) is running `node --max_old_space_size=4096 node_modules/.bin/webpack-dev-server --progress --color --config config/webpack/development.js`. That completes the whole process and then running `rails s` works as well.

**Comment by JeGoi** [comment] 2018-04-17 14:49
@LocoDelAssembly Hum, you are right. The settings are 10240 so not exactly [as what it is describe here](https://www.npmjs.com/package/increase-memory-limit). Well, it's due to that https://github.com/endel/increase-memory-limit/blob/master/index.js#L6

I've tried `$ node --max_old_space_size=4096 node_modules/.bin/webpack-dev-server --progress --color --config config/webpack/development.js` but without success from now. I've also increased the VM's RAM to 4508 MB. (I should have done the same for the CPU...) And it still like this for the last 5 minutes ...

![image](https://user-images.githubusercontent.com/13801368/38877329-78be62a4-422c-11e8-860f-77298f167fcf.png)

**Comment by LocoDelAssembly** [comment] 2018-04-17 15:51
When I run the command it completes in about 2 minutes with the **new 16.04.*4*** VM.

You should try the new VM but **first** please confirm me something. What does happen when you use `increase-memory-limit` and then `./bin/webpack-dev-server`? Does it freeze (see terminal output below) or it continues with the out of memory problem? With the **new** VM it freezes right from the beginning, no output whatsoever and fails with the out of memory problem if the node bins are not patched.

```
taxonworks@TW-VirtualBox:~/Projects/taxonworks$ sudo npm install -g increase-memory-limit
[sudo] password for taxonworks: 
/usr/bin/increase-memory-limit -> /usr/lib/node_modules/increase-memory-limit/index.js
+ increase-memory-limit@1.0.6
added 12 packages in 2.698s
taxonworks@TW-VirtualBox:~/Projects/taxonworks$ LIMIT=4096 increase-memory-limit 
'node_modules/.bin/acorn' written successfully.
'node_modules/.bin/ansi-html' written successfully.
'node_modules/.bin/atob' written successfully.
'node_modules/.bin/autoprefixer-info' written successfully.
'node_modules/.bin/babylon' written successfully.
'node_modules/.bin/browserslist' written successfully.
'node_modules/.bin/cssesc' written successfully.
'node_modules/.bin/csso' written successfully.
'node_modules/.bin/errno' written successfully.
'node_modules/.bin/eslint' written successfully.
'node_modules/.bin/esparse' written successfully.
'node_modules/.bin/esvalidate' written successfully.
'node_modules/.bin/gonzales' written successfully.
'node_modules/.bin/har-validator' written successfully.
'node_modules/.bin/he' written successfully.
'node_modules/.bin/import-local-fixture' written successfully.
'node_modules/.bin/in-install' written successfully.
'node_modules/.bin/in-publish' written successfully.
'node_modules/.bin/internal-ip' written successfully.
'node_modules/.bin/js-yaml' written successfully.
'node_modules/.bin/jsesc' written successfully.
'node_modules/.bin/json5' written successfully.
'node_modules/.bin/loose-envify' written successfully.
'node_modules/.bin/miller-rabin' written successfully.
'node_modules/.bin/mime' written successfully.
'node_modules/.bin/mkdirp' written successfully.
'node_modules/.bin/multicast-dns' written successfully.
'node_modules/.bin/node-gyp' written successfully.
'node_modules/.bin/node-sass' written successfully.
'node_modules/.bin/nopt' written successfully.
'node_modules/.bin/not-in-install' written successfully.
'node_modules/.bin/not-in-publish' written successfully.
'node_modules/.bin/prettier' written successfully.
'node_modules/.bin/regjsparser' written successfully.
'node_modules/.bin/rgb' written successfully.
'node_modules/.bin/rimraf' written successfully.
'node_modules/.bin/sassgraph' written successfully.
'node_modules/.bin/semver' written successfully.
'node_modules/.bin/sha.js' written successfully.
'node_modules/.bin/sshpk-conv' written successfully.
'node_modules/.bin/sshpk-sign' written successfully.
'node_modules/.bin/sshpk-verify' written successfully.
'node_modules/.bin/strip-indent' written successfully.
'node_modules/.bin/stylus' written successfully.
'node_modules/.bin/svgo' written successfully.
'node_modules/.bin/uglifyjs' written successfully.
'node_modules/.bin/uuid' written successfully.
'node_modules/.bin/webpack' written successfully.
'node_modules/.bin/webpack-dev-server' written successfully.
'node_modules/.bin/which' written successfully.
taxonworks@TW-VirtualBox:~/Projects/taxonworks$ time ./bin/webpack-dev-server 
^C

real	1m18.926s
user	0m20.301s
sys	0m56.822s
```

**Comment by JeGoi** [comment] 2018-04-17 16:55
increase-memory-limit is working.
Oh! Yes, confirm, it freezes:
```
taxonworks@TW-VirtualBox:~/Projects/taxonworks$ time ./bin/webpack-dev-server
^C

real	2m42.377s
user	1m13.012s
sys	1m28.291s
```

**Comment by LocoDelAssembly** [comment] 2018-04-17 17:08
I used `strace` and discovered that it is trapped in an infinite loop trying to run the file over and over... In fact there is no need to use `./bin/webpack-dev-server` to trigger this bug, you may use `./node_modules/.bin/webpack-dev-server --progress --color --config config/webpack/development.js`. It is like `usr/bin/env` doesn't like arguments to be set on the shebang line... It works fine if I replace the shebang with `#!/usr/bin/node --max-old-space-size=4096`.

Can't figure out why is this happening and can't find anything on the Internet either...

**Comment by JeGoi** [comment] 2018-04-17 17:33
@LocoDelAssembly Yes, confirmed, it's working with your modification.

```
      _/_/node_modules/@ibm/type/fonts/Serif/web/woff/IBMPlexSerif-SemiBoldItalic-Latin1-0f07dfdd74a96f56ebdb503a11ac6848.woff  27.1 kB          
       [0] ./node_modules/css-loader?{"minimize":false,"sourceMap":true,"importLoaders":2}!./node_modules/postcss-loader/lib?{"sourceMap":true,"config":{"path":"/home/taxonworks/Projects/taxonworks/.postcssrc.yml"}}!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./app/javascript/packs/style/application.scss 140 kB {0} [built]
       [2] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
       [3] ./node_modules/@ibm/type/fonts/Mono/web/woff2/IBMPlexMono-Italic-Pi.woff2 154 bytes {0} [built]
       [4] ./node_modules/@ibm/type/fonts/Mono/web/woff/IBMPlexMono-Italic-Pi.woff 152 bytes {0} [built]
       [5] ./node_modules/@ibm/type/fonts/Mono/web/woff2/IBMPlexMono-Italic-Latin3.woff2 158 bytes {0} [built]
       [6] ./node_modules/@ibm/type/fonts/Mono/web/woff/IBMPlexMono-Italic-Latin3.woff 156 bytes {0} [built]
       [7] ./node_modules/@ibm/type/fonts/Mono/web/woff2/IBMPlexMono-Italic-Latin2.woff2 158 bytes {0} [built]
       [8] ./node_modules/@ibm/type/fonts/Mono/web/woff/IBMPlexMono-Italic-Latin2.woff 156 bytes {0} [built]
       [9] ./node_modules/@ibm/type/fonts/Mono/web/woff2/IBMPlexMono-Italic-Latin1.woff2 158 bytes {0} [built]
      [10] ./node_modules/@ibm/type/fonts/Mono/web/woff/IBMPlexMono-Italic-Latin1.woff 156 bytes {0} [built]
      [11] ./node_modules/@ibm/type/fonts/Mono/web/woff2/IBMPlexMono-Regular-Pi.woff2 155 bytes {0} [built]
      [12] ./node_modules/@ibm/type/fonts/Mono/web/woff/IBMPlexMono-Regular-Pi.woff 153 bytes {0} [built]
      [13] ./node_modules/@ibm/type/fonts/Mono/web/woff2/IBMPlexMono-Regular-Latin3.woff2 159 bytes {0} [built]
      [14] ./node_modules/@ibm/type/fonts/Mono/web/woff/IBMPlexMono-Regular-Latin3.woff 157 bytes {0} [built]
     [114] ./node_modules/@ibm/type/fonts/Serif/web/woff/IBMPlexSerif-SemiBoldItalic-Latin1.woff 166 bytes {0} [built]
        + 100 hidden modules
webpack: Compiled successfully.
^C

```

![image](https://user-images.githubusercontent.com/13801368/38886533-3c2b84c6-4244-11e8-91fc-da35c5907494.png)

**Comment by JeGoi** [comment] 2018-04-17 17:47
Perhaps, this should help: https://unix.stackexchange.com/a/361795

**Comment by LocoDelAssembly** [comment] 2018-04-17 17:56
OK, found something. Looks that Linux capabilities to process the shebang are pretty limited: https://unix.stackexchange.com/questions/63979/shebang-line-with-usr-bin-env-command-argument-fails-on-linux

However, `NODE_OPTIONS='--max_old_space_size=4096' ./bin/webpack-dev-server` seems to work with unmodified node bins (on new VM, not sure the old one that was built with Node v6 rather than v8).

I strongly suggest using this approach and abandon `increase-memory-limit` altogether. Will update instructions to use the method above.

[edit]Sorry, was interrupted in the middle of posting and didn't see you link. But yes, clearly increase-memory-limit wont work ever, and even for systems it does work it is still not totally advised because updating the node packages will remove the shebang patch.[/edit]

**Comment by LocoDelAssembly** [comment] 2018-04-17 19:42
Fixed in https://github.com/SpeciesFileGroup/taxonworks/commit/985e590e93a38e65d284e7380977b632b921e5e4

Thanks @JeGoi for finding the bug and assisting in fixing it. Please re-open if you still have trouble with this particular problem.

**Closed as completed by LocoDelAssembly** 2018-04-17 19:42 UTC
Labels: bug

**Comment by JeGoi** [comment] 2018-04-20 14:13
@LocoDelAssembly and @mjy no worries. Thanks for your amazing job.
